// Related to validation
export const ACTION_VALIDATION_FAILED = "VALIDATION_FAILED";

// Related to Login Check.
export const ACTION_CHECK_LOGIN_STARTED = "CHECK_LOGIN_STARTED";
export const ACTION_CHECK_LOGIN_EXIST = "CHECK_LOGIN_EXIST";
export const ACTION_CHECK_LOGIN_NOTEXIST = "CHECK_LOGIN_NOTEXIST";
export const ACTION_CHECK_LOGIN_FAILED = "CHECK_LOGIN_FAILED";

// Related to Login.
export const ACTION_LOGIN_STARTED = "LOGIN_STARTED";
export const ACTION_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ACTION_LOGIN_FAILED = "LOGIN_FAILED";

//
export const ACTION_GET_USER_TYPES_STARTED = "GET_USER_TYPES_STARTED";
export const ACTION_GET_USER_TYPES_FAILED = "GET_USER_TYPES_FAILED";
export const ACTION_GET_USER_TYPES_SUCCESS = "GET_USER_TYPES_SUCCESS";

//
export const ACTION_GET_PRIORITIES_STARTED = "GET_PRIORITIES_STARTED";
export const ACTION_GET_PRIORITIES_FAILED = "GET_PRIORITIES_FAILED";
export const ACTION_GET_PRIORITIES_SUCCESS = "GET_PRIORITIES_SUCCESS";


//
export const ACTION_GET_ALL_CASES_STARTED = "GET_ALL_CASES_STARTED";
export const ACTION_GET_ALL_CASES_FAILED = "GET_ALL_CASES_FAILED";
export const ACTION_GET_ALL_CASES_SUCCESS = "GET_ALL_CASES_SUCCESS";

//
export const ACTION_UPDATE_CASES_STARTED = "UPDATE_CASES_STARTED";
export const ACTION_UPDATE_CASES_FAILED = "UPDATE_CASES_FAILED";
export const ACTION_UPDATE_CASES_SUCCESS = "UPDATE_CASES_SUCCESS";

//
export const ACTION_GET_ALL_DEPARTMENTS_STARTED = "GET_ALL_DEPARTMENTS_STARTED";
export const ACTION_GET_ALL_DEPARTMENTS_FAILED = "GET_ALL_DEPARTMENTS_FAILED";
export const ACTION_GET_ALL_DEPARTMENTS_SUCCESS = "GET_ALL_DEPARTMENTS_SUCCESS";


//
export const ACTION_CREATE_CASES_STARTED = "CREATE_CASES_STARTED";
export const ACTION_CREATE_CASES_SUCCESS = "CREATE_CASES_SUCCESS";
export const ACTION_CREATE_CASES_FAILED = "CREATE_CASES_FAILED";


//
export const ACTION_LOGOUT_FAILED = "fail"
export const ACTION_LOGOUT_STARTED = "start"
export const ACTION_LOGGED_OUT = "OUT"



